import csv
import io

data = """item_id,category,item_name,size,price_pkr,status
1,Pulao,Single,Regular,645,Available
2,Pulao,Single Choice,Regular,665,Available
3,Pulao,Single Without Kabab,Regular,585,Available
4,Pulao,Special Choice,Large,845,Available
5,Pulao,Pulao,Regular,335,Available
6,Pulao,Pulao Kabab,Regular,445,Available
7,Pulao,Chicken Piece Addon,Single,205,Available
8,Pulao,Shami Kabab Addon,Single,65,Available
9,Pulao,Raita Extra,Small,35,Available
10,Pulao,Salad Extra,Small,35,Available
11,Burgers,Krispo Burger,Regular,610,Available
12,Burgers,Krispo Burger Cheese,Regular,660,Available
13,Burgers,Krispo Burger Fries Combo,Regular,810,Available
14,Burgers,Chicken Burger,Regular,510,Available
15,Burgers,Chicken Burger Fries Combo,Regular,705,Available
16,Burgers,Zinger Burger,Regular,650,Available
17,Burgers,Zinger Cheese Burger,Regular,720,Available
18,Burgers,Double Patty Burger,Large,890,Available
19,Burgers,Beef Burger,Regular,690,Available
20,Burgers,Kids Burger,Small,420,Available
21,Fried,Krispo Wings 4 pcs,Regular,349,Available
22,Fried,Krispo Wings 6 pcs,Regular,449,Available
23,Fried,Krispo Wings 10 pcs,Large,699,Available
24,Fried,Krispo Chicken Piece,Single,299,Available
25,Fried,Krispo Chicken 2 Piece,Regular,540,Available
26,Fried,French Fries Small,Small,225,Available
27,Fried,French Fries Medium,Medium,275,Available
28,Fried,French Fries Large,Large,355,Available
29,Fried,Nuggets 6 pcs,Regular,399,Available
30,Fried,Nuggets 10 pcs,Regular,599,Available
31,Deals,My Deal,Regular,999,Available
32,Deals,Burger Deal 1,Regular,899,Available
33,Deals,Burger Deal 2,Regular,1399,Available
34,Deals,Family Deal 1,Large,2499,Available
35,Deals,Family Deal 2,Large,3299,Available
36,Deals,Wings Combo,Regular,799,Available
37,Deals,Student Deal,Regular,699,Available
38,Deals,Lunch Deal,Regular,745,Available
39,Deals,Dinner Deal,Regular,899,Available
40,Deals,Weekend Deal,Large,1799,Available
41,Desserts,Kheer Cup,Small,210,Available
42,Desserts,Kheer Box 3 Serving,Medium,560,Available
43,Desserts,Kheer 1 Kg,Regular,850,Available
44,Desserts,Kheer 2 Kg,Large,1600,Available
45,Desserts,Kheer 5 Kg,Bulk,3900,Available
46,Desserts,Zarda Cup,Small,195,Available
47,Desserts,Zarda Box,Medium,525,Available
48,Desserts,Ice Cream One Scoop,Small,180,Available
49,Desserts,Ice Cream Two Scoop,Regular,320,Available
50,Desserts,Falooda,Regular,350,Available
51,Beverages,Tea Cup,Regular,130,Available
52,Beverages,Milk Coffee,Regular,199,Available
53,Beverages,Soft Drink Can Pepsi,250ml,120,Available
54,Beverages,Soft Drink Can 7up,250ml,120,Available
55,Beverages,Soft Drink Can Mirinda,250ml,120,Available
56,Beverages,Soft Drink 500ml,500ml,140,Available
57,Beverages,Soft Drink 1 Liter,1L,220,Available
58,Beverages,Soft Drink 1.5 Liter,1.5L,280,Available
59,Beverages,Water 500ml,500ml,75,Available
60,Beverages,Water 1.5 Liter,1.5L,120,Available
61,Beverages,Savour Water 19L New,19L,420,Available
62,Beverages,Savour Water 19L Refill,19L,220,Available
63,Daig,Sada Pulao Daig,Small,4500,Available
64,Daig,Sada Pulao Daig,Medium,7800,Available
65,Daig,Sada Pulao Daig,Large,12500,Available
66,Daig,Chicken Pulao Daig,Small,6200,Available
67,Daig,Chicken Pulao Daig,Medium,10500,Available
68,Daig,Chicken Pulao Daig,Large,16500,Available
69,Daig,Beef Pulao Daig,Small,7600,Available
70,Daig,Beef Pulao Daig,Medium,13200,Available
71,Daig,Beef Pulao Daig,Large,21000,Available
72,Daig,Mutton Pulao Daig,Small,9200,Available
73,Daig,Mutton Pulao Daig,Medium,15800,Available
74,Daig,Mutton Pulao Daig,Large,25500,Available
75,Daig,Chana Pulao Daig,Small,3900,Available
76,Daig,Chana Pulao Daig,Medium,6500,Available
77,Daig,Chana Pulao Daig,Large,9900,Available
78,Sides,Ketchup Sachet,Single,12,Available
79,Sides,Garlic Dip,Single,35,Available
80,Sides,Chili Garlic Sauce,Single,35,Available
81,Sides,Extra Cheese Slice,Single,80,Available
82,Sides,Bread Bun,Single,45,Available
83,Sides,Disposable Plate,Single,10,Available
84,Sides,Spoon Fork Set,Single,15,Available
85,Sides,Family Raita,Large,120,Available
86,Sides,Family Salad,Large,120,Available
87,Breakfast,Halwa Puri,Regular,420,Available
88,Breakfast,Chana Plate,Regular,220,Available
89,Breakfast,Naan Pair,Regular,80,Available
90,Breakfast,Anda Paratha,Regular,260,Available
91,Breakfast,Omelette Toast,Regular,295,Available
92,Seasonal,Ramzan Deal 1,Regular,899,Seasonal
93,Seasonal,Ramzan Deal 2,Large,1499,Seasonal
94,Seasonal,Eid Family Deal,Large,3599,Seasonal
95,Seasonal,Winter Soup Cup,Regular,280,Seasonal
96,Seasonal,Summer Lassi,Regular,220,Seasonal"""

reader = csv.DictReader(io.StringIO(data))

sql = """-- Step 1: Drop old tables
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS menu_items;

-- Step 2: Create the new Savour Foods menu table
CREATE TABLE menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text,
  price numeric(10, 2) not null,
  available boolean default true
);

-- Step 3: Insert Savour Foods menu data
INSERT INTO menu_items (id, name, category, description, price, available) VALUES
"""

values = []
for row in reader:
    id_val = row["item_id"]
    cat = row["category"].replace("'", "''")
    name = row["item_name"].replace("'", "''")
    size = row["size"].replace("'", "''")
    price = row["price_pkr"]
    avail = "true" if row["status"] in ["Available", "Seasonal"] else "false"
    values.append(f"({id_val}, '{name}', '{cat}', '{size}', {price}, {avail})")

sql += ",\n".join(values) + ";\n"

sql += """
-- Step 4: Create the orders table
CREATE TABLE IF NOT EXISTS orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  status text not null default 'pending',
  -- status values: pending | confirmed | preparing | ready | delivered | cancelled
  total numeric(10, 2) not null default 0,
  created_at timestamptz default now()
);

-- Step 5: Create the order_items table (line items per order)
CREATE TABLE IF NOT EXISTS order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade not null,
  menu_item_id bigint references menu_items(id) not null,
  quantity int not null default 1,
  unit_price numeric(10, 2) not null
);
"""

with open('c:\\\\Users\\\\Lenovo\\\\.antigravity\\\\voiceAI db\\\\savour_menu_schema.sql', 'w') as f:
    f.write(sql)
