-- Step 1: Drop the old items table if it exists
DROP TABLE IF EXISTS items;

-- Step 2: Create the new KFC menu table
CREATE TABLE menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text,
  price numeric(10, 2) not null,
  available boolean default true
);

-- Step 3: Insert dummy KFC menu data
INSERT INTO menu_items (name, category, description, price, available) VALUES
  -- Burgers
  ('Zinger Burger', 'Burgers', 'Crispy spicy chicken fillet in a sesame bun with lettuce and mayo', 7.99, true),
  ('Tower Burger', 'Burgers', 'Double chicken fillet with cheese, bacon, and BBQ sauce', 9.49, true),
  ('Fillet Burger', 'Burgers', 'Classic crispy chicken fillet with fresh lettuce and creamy mayo', 6.99, true),

  -- Chicken
  ('Original Recipe Chicken (3 pcs)', 'Chicken', 'KFC signature hand-breaded fried chicken', 11.99, true),
  ('Extra Crispy Chicken (3 pcs)', 'Chicken', 'Extra crunchy version of KFC classic chicken', 12.49, true),
  ('Hot Wings (6 pcs)', 'Chicken', 'Spicy crispy chicken wings with fiery seasoning', 8.99, true),
  ('Popcorn Chicken (Large)', 'Chicken', 'Bite-sized chunks of crispy seasoned chicken', 5.99, true),

  -- Sides
  ('Coleslaw', 'Sides', 'Creamy homestyle coleslaw', 2.49, true),
  ('Corn on the Cob', 'Sides', 'Sweet corn grilled to perfection', 2.99, true),
  ('Mashed Potatoes', 'Sides', 'Creamy mashed potatoes with gravy', 3.49, true),
  ('French Fries (Large)', 'Sides', 'Crispy golden fries', 3.99, true),
  ('Mac & Cheese', 'Sides', 'Creamy macaroni and cheese', 3.99, true),

  -- Drinks
  ('Pepsi (Large)', 'Drinks', 'Chilled Pepsi cola', 2.49, true),
  ('7UP (Large)', 'Drinks', 'Refreshing lemon-lime soda', 2.49, true),
  ('Mountain Dew (Large)', 'Drinks', 'Citrus Mountain Dew', 2.49, true),

  -- Desserts
  ('Chocolate Mousse Cake', 'Desserts', 'Rich chocolate mousse layered cake', 3.99, true),
  ('Soft Serve Ice Cream', 'Desserts', 'Creamy vanilla soft serve', 1.99, true);
