-- ============================================================
-- SAVOUR FOODS — Supabase SQL Schema
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- ============================================================

-- Step 1: Drop existing tables (clean slate)
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS menu_items CASCADE;

-- ============================================================
-- Step 2: Create menu_items table
-- ============================================================
CREATE TABLE menu_items (
  id          bigint generated by default as identity primary key,
  name        text not null,
  category    text not null,
  size        text,
  price       numeric(10, 2) not null,
  available   boolean default true
);

-- ============================================================
-- Step 3: Insert Savour Foods menu data (96 items, 10 categories)
-- ============================================================
INSERT INTO menu_items (id, name, category, size, price, available) VALUES

-- ── PULAO ──────────────────────────────────────────────────
(1,  'Single',               'Pulao',      'Regular', 645,   true),
(2,  'Single Choice',        'Pulao',      'Regular', 665,   true),
(3,  'Single Without Kabab', 'Pulao',      'Regular', 585,   true),
(4,  'Special Choice',       'Pulao',      'Large',   845,   true),
(5,  'Pulao',                'Pulao',      'Regular', 335,   true),
(6,  'Pulao Kabab',          'Pulao',      'Regular', 445,   true),
(7,  'Chicken Piece Addon',  'Pulao',      'Single',  205,   true),
(8,  'Shami Kabab Addon',    'Pulao',      'Single',  65,    true),
(9,  'Raita Extra',          'Pulao',      'Small',   35,    true),
(10, 'Salad Extra',          'Pulao',      'Small',   35,    true),

-- ── BURGERS ────────────────────────────────────────────────
(11, 'Krispo Burger',             'Burgers', 'Regular', 610,  true),
(12, 'Krispo Burger Cheese',      'Burgers', 'Regular', 660,  true),
(13, 'Krispo Burger Fries Combo', 'Burgers', 'Regular', 810,  true),
(14, 'Chicken Burger',            'Burgers', 'Regular', 510,  true),
(15, 'Chicken Burger Fries Combo','Burgers', 'Regular', 705,  true),
(16, 'Zinger Burger',             'Burgers', 'Regular', 650,  true),
(17, 'Zinger Cheese Burger',      'Burgers', 'Regular', 720,  true),
(18, 'Double Patty Burger',       'Burgers', 'Large',   890,  true),
(19, 'Beef Burger',               'Burgers', 'Regular', 690,  true),
(20, 'Kids Burger',               'Burgers', 'Small',   420,  true),

-- ── FRIED ──────────────────────────────────────────────────
(21, 'Krispo Wings 4 pcs',    'Fried', 'Regular', 349,  true),
(22, 'Krispo Wings 6 pcs',    'Fried', 'Regular', 449,  true),
(23, 'Krispo Wings 10 pcs',   'Fried', 'Large',   699,  true),
(24, 'Krispo Chicken Piece',  'Fried', 'Single',  299,  true),
(25, 'Krispo Chicken 2 Piece','Fried', 'Regular', 540,  true),
(26, 'French Fries Small',    'Fried', 'Small',   225,  true),
(27, 'French Fries Medium',   'Fried', 'Medium',  275,  true),
(28, 'French Fries Large',    'Fried', 'Large',   355,  true),
(29, 'Nuggets 6 pcs',         'Fried', 'Regular', 399,  true),
(30, 'Nuggets 10 pcs',        'Fried', 'Regular', 599,  true),

-- ── DEALS ──────────────────────────────────────────────────
(31, 'My Deal',       'Deals', 'Regular', 999,  true),
(32, 'Burger Deal 1', 'Deals', 'Regular', 899,  true),
(33, 'Burger Deal 2', 'Deals', 'Regular', 1399, true),
(34, 'Family Deal 1', 'Deals', 'Large',   2499, true),
(35, 'Family Deal 2', 'Deals', 'Large',   3299, true),
(36, 'Wings Combo',   'Deals', 'Regular', 799,  true),
(37, 'Student Deal',  'Deals', 'Regular', 699,  true),
(38, 'Lunch Deal',    'Deals', 'Regular', 745,  true),
(39, 'Dinner Deal',   'Deals', 'Regular', 899,  true),
(40, 'Weekend Deal',  'Deals', 'Large',   1799, true),

-- ── DESSERTS ───────────────────────────────────────────────
(41, 'Kheer Cup',          'Desserts', 'Small',   210,  true),
(42, 'Kheer Box 3 Serving','Desserts', 'Medium',  560,  true),
(43, 'Kheer 1 Kg',         'Desserts', 'Regular', 850,  true),
(44, 'Kheer 2 Kg',         'Desserts', 'Large',   1600, true),
(45, 'Kheer 5 Kg',         'Desserts', 'Bulk',    3900, true),
(46, 'Zarda Cup',          'Desserts', 'Small',   195,  true),
(47, 'Zarda Box',          'Desserts', 'Medium',  525,  true),
(48, 'Ice Cream One Scoop','Desserts', 'Small',   180,  true),
(49, 'Ice Cream Two Scoop','Desserts', 'Regular', 320,  true),
(50, 'Falooda',            'Desserts', 'Regular', 350,  true),

-- ── BEVERAGES ──────────────────────────────────────────────
(51, 'Tea Cup',                'Beverages', 'Regular', 130,  true),
(52, 'Milk Coffee',            'Beverages', 'Regular', 199,  true),
(53, 'Soft Drink Can Pepsi',   'Beverages', '250ml',   120,  true),
(54, 'Soft Drink Can 7up',     'Beverages', '250ml',   120,  true),
(55, 'Soft Drink Can Mirinda', 'Beverages', '250ml',   120,  true),
(56, 'Soft Drink 500ml',       'Beverages', '500ml',   140,  true),
(57, 'Soft Drink 1 Liter',     'Beverages', '1L',      220,  true),
(58, 'Soft Drink 1.5 Liter',   'Beverages', '1.5L',    280,  true),
(59, 'Water 500ml',            'Beverages', '500ml',   75,   true),
(60, 'Water 1.5 Liter',        'Beverages', '1.5L',    120,  true),
(61, 'Savour Water 19L New',   'Beverages', '19L',     420,  true),
(62, 'Savour Water 19L Refill','Beverages', '19L',     220,  true),

-- ── DAIG (Bulk Catering) ────────────────────────────────────
(63, 'Sada Pulao Daig',    'Daig', 'Small',  4500,  true),
(64, 'Sada Pulao Daig',    'Daig', 'Medium', 7800,  true),
(65, 'Sada Pulao Daig',    'Daig', 'Large',  12500, true),
(66, 'Chicken Pulao Daig', 'Daig', 'Small',  6200,  true),
(67, 'Chicken Pulao Daig', 'Daig', 'Medium', 10500, true),
(68, 'Chicken Pulao Daig', 'Daig', 'Large',  16500, true),
(69, 'Beef Pulao Daig',    'Daig', 'Small',  7600,  true),
(70, 'Beef Pulao Daig',    'Daig', 'Medium', 13200, true),
(71, 'Beef Pulao Daig',    'Daig', 'Large',  21000, true),
(72, 'Mutton Pulao Daig',  'Daig', 'Small',  9200,  true),
(73, 'Mutton Pulao Daig',  'Daig', 'Medium', 15800, true),
(74, 'Mutton Pulao Daig',  'Daig', 'Large',  25500, true),
(75, 'Chana Pulao Daig',   'Daig', 'Small',  3900,  true),
(76, 'Chana Pulao Daig',   'Daig', 'Medium', 6500,  true),
(77, 'Chana Pulao Daig',   'Daig', 'Large',  9900,  true),

-- ── SIDES ──────────────────────────────────────────────────
(78, 'Ketchup Sachet',    'Sides', 'Single', 12,   true),
(79, 'Garlic Dip',        'Sides', 'Single', 35,   true),
(80, 'Chili Garlic Sauce','Sides', 'Single', 35,   true),
(81, 'Extra Cheese Slice','Sides', 'Single', 80,   true),
(82, 'Bread Bun',         'Sides', 'Single', 45,   true),
(83, 'Disposable Plate',  'Sides', 'Single', 10,   true),
(84, 'Spoon Fork Set',    'Sides', 'Single', 15,   true),
(85, 'Family Raita',      'Sides', 'Large',  120,  true),
(86, 'Family Salad',      'Sides', 'Large',  120,  true),

-- ── BREAKFAST ──────────────────────────────────────────────
(87, 'Halwa Puri',    'Breakfast', 'Regular', 420,  true),
(88, 'Chana Plate',   'Breakfast', 'Regular', 220,  true),
(89, 'Naan Pair',     'Breakfast', 'Regular', 80,   true),
(90, 'Anda Paratha',  'Breakfast', 'Regular', 260,  true),
(91, 'Omelette Toast','Breakfast', 'Regular', 295,  true),

-- ── SEASONAL ───────────────────────────────────────────────
(92, 'Ramzan Deal 1',    'Seasonal', 'Regular', 899,  true),
(93, 'Ramzan Deal 2',    'Seasonal', 'Large',   1499, true),
(94, 'Eid Family Deal',  'Seasonal', 'Large',   3599, true),
(95, 'Winter Soup Cup',  'Seasonal', 'Regular', 280,  true),
(96, 'Summer Lassi',     'Seasonal', 'Regular', 220,  true);

-- ============================================================
-- Step 4: Create orders table
-- ============================================================
CREATE TABLE orders (
  id            bigint generated by default as identity primary key,
  customer_name text not null,
  status        text not null default 'pending'
                  CHECK (status IN ('pending', 'confirmed', 'delivered', 'cancelled')),
  total         numeric(10, 2) not null default 0,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- Auto-update updated_at on every row change
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- Step 5: Create order_items table
-- ============================================================
CREATE TABLE order_items (
  id           bigint generated by default as identity primary key,
  order_id     bigint references orders(id) on delete cascade not null,
  menu_item_id bigint references menu_items(id) not null,
  quantity     int not null default 1 CHECK (quantity > 0),
  unit_price   numeric(10, 2) not null
);

-- ============================================================
-- Verification: Check all tables were created & row counts
-- ============================================================
SELECT 'menu_items'  AS table_name, COUNT(*) AS rows FROM menu_items
UNION ALL
SELECT 'orders',       COUNT(*) FROM orders
UNION ALL
SELECT 'order_items',  COUNT(*) FROM order_items;
